### ISSUE TITLE
Waves and Bootstrap

### ISSUE THREAD

**Issue by nonameolsson** [fians/Waves#107]
Hi!
I've been trying to add Waves to our web app, but I have problems with the buttons.

**Method 1:**
```<a href="#" class="btn btn-primary waves-effect waves-float waves-button">My button</a>```
It seems like that the waves-button class overrides some of the Bootstrap classes from btn-primary. For example the background and text color doesn't work, it ends up with a transparent background and a black text.

**Method 2:**
```<a href="#" class="btn btn-primary waves-effect waves-float">My button</a>```
Removing waves-button class the colors from btn-primary are applied, but the button styling from waves are of course missing. 

**Ugly** *hack* to make it work:
The only way I've managed it to work is to re-declare all the Bootstrap btn-* styles and add !important. 
```
.btn.btn-primary {
    background: $btn-primary-bg !important;
    color: $btn-primary-color: !important;
}
<a href="#" class="btn btn-primary waves-effect waves-float waves-button">My button</a>
```
But this is not a good way, and I don't think that we will be able to use this method. 

Do you have any idea how to make Waves play nice with Bootstrap?

**Comment by sqal** [comment]
+1 I wanted to open an issue about the same matter. I thinks the best option here will be separating core/basic waves styles from all the styles that could overrides user styles and put them e.g. waves-theme.scss

**Comment by fians** [comment]
I think it's hard to integrated Waves with Bootstrap without additional css style, since Waves only works on flat surface (solid color) and bootstrap's button itself has some skeuomorphism style (bevels and emboss, like github green comment button).
