### ISSUE TITLE
JSHint found some issues

### ISSUE THREAD

**Issue by ThemeSama** [fians/Waves#114]
Hi Fians,

Line 181 - Extra comma. (it breaks older versions of IE) - I think this is not important :)
Line 15,16 - 'define' is not defined.
Line 24 - 'module' is not defined.
Line 31 - 'global' is not defined.
Line 142 - 'width' is defined but never used.

If statements available but I can't passed on JSHint for 15, 16, 24 and 31. lines.

**Comment by hoxxep** [comment]
Have you made any modifications to the source?

We run all our code through JSHint in Grunt while developing, and the build will fail if JSHint finds any errors. This means the repository should pass JSHint (it is for me, on both the v0.7.0-dev and master branches). We use `grunt-contrib-jshint` version `0.10.0`; so perhaps you're using a different JSHint version? Plus, our Gruntfile JSHint config allows globals:

```javascript
jshint: {
    files: [
        // ...
    ],
    options: {
        globals: {
            console: true
        }
    }
},
```

Are you using our Gruntfile to initiate JSHint, or another JSHint? Lines 10-30 are an [AMD (Asynchronous Module Definition)](http://requirejs.org/docs/whyamd.html), hence why `define` and `module` aren't defined as they're to be provided by AMD or CJS-like environments through global variables.

Also, there is no `width` variable at line 142 on either the `master` or `v0.7.0-dev` branches? Actually, `waves.js` has no `width` variable anywhere? I'm not sure why that error is occurring. I have seen the extra comma, I've now removed it for v0.7.0.

I'd update to the latest build on `master` and configure JSHint to accept globals, that should remove all JSHint errors.

**Comment by ThemeSama** [comment]
I'm looking this file https://github.com/fians/Waves/blob/master/src/js/waves.js 142. line

```javascript
var width = el.clientWidth * 1.4;
```

I'm using Bootstrap and some special configs available. "grunt-contrib-jshint": "~0.11.0"
https://github.com/twbs/bootstrap/blob/master/js/.jshintrc

How can I pass this notifications with original release? I removed some lines and working Waves with Bootstrap v3.3.2.

Original:
```javascript
;(function(window, factory) {
    "use strict";

    // AMD. Register as an anonymous module.  Wrap in function so we have access
    // to root via `this`.
    if (typeof define === "function" && define.amd) {
        define([], function() {
            return factory.apply(window);
        });
    }

    // Node. Does not work with strict CommonJS, but only CommonJS-like
    // environments that support module.exports, like Node.
    else if (typeof exports === "object") {
        module.exports = factory.call(window);
    }

    // Browser globals.
    else {
        window.Waves = factory.call(window);
    }
})(typeof global === "object" ? global : this, function () {
```
My used:
```javascript
;(function(window, factory) {
  "use strict";
  window.Waves = factory.call(window);
})(this, function () {
```

**Comment by ThemeSama** [comment]
I'm used v.0.7.0-dev JS file and new issues available. I just moved this functions and I passed.

```
424 |        function allowRipple(element) {
                 ^ 'allowRipple' was used before it was defined.
544 |        function hideRipple(mouseup, element) {
                 ^ 'hideRipple' was used before it was defined.
```

allowRipple moved 406. line
hideRipple moved 513. line

**Comment by ThemeSama** [comment]
OK I added this lines and I passed :)
```javascript
/*global define, module, global*/
;(function(window, factory) {
...
```
