### ISSUE TITLE
removeRipple() randomly causes error -  'Cannot read property 'classList' of undefined' 

### ISSUE THREAD

**Issue by sqal** [fians/Waves#119]
Steps to reproduce the issue:

1. Go to examples page -  http://fian.my.id/Waves/#examples
2. Open the browser console 
3. Using the example with image, click on the bottom left corner of image, then very quickly click on the opposite corner.

At some point in the console you should notice an error:

`Uncaught TypeError: Cannot read property 'classList' of undefined`

This is happening, because `ripple` argument in removeRipple function is in that case `undefined`. Sadly, I was able to track down the problem only to this point. Hopefully someone will have more luck with this.

**Comment by fians** [comment]
It's caching problem. Let me try to fix it by adding parameter on the static source.

**Comment by sqal** [comment]
No, that is not the issue here. Check out this way. Open the browser console on Elements tab find `.img-wrapper` and play with Waves clicking very fast in different places of the image. You'll notice that one `.waves-ripple'` div  is not removed as it should, untill you move the cursor out of the image. So, there's problem with Show/Hide function logic, I think.

**Comment by fians** [comment]
It's working fine for me. What browser do you use when find this issue? And also its version.

**Comment by sqal** [comment]
Any browser.It's it's strange that you can't reproduce this bug. Here, take a look at this -  https://www.screenr.com/NiJN

**Comment by fians** [comment]
Can you create a jsfiddle of it?

**Comment by sqal** [comment]
Here you go, but it's only copy/paste the latest verions of Waves - http://jsfiddle.net/9u7hhcuu/

**Comment by sqal** [comment]
Ok, I think I figured it out, can send PR but have a couple of questions first:

1. What is `waves-rippling` class in line [120](https://github.com/fians/Waves/blob/master/src/js/waves.js#L120) added for? Wasn't this part of PR #110 and then removed in b59ecfe154311f1 ? Seems unnecessary to me

2. What is the point of checking for mousemove event? e.g in here [243](https://github.com/fians/Waves/blob/master/src/js/waves.js#L243) and a few other places. I don't see anywhere that this event is bound to an element (it was part of drag functionality [496](https://github.com/fians/Waves/commit/b59ecfe154311f1f96c7adb094fda0c8cd7aa4ea#diff-6988341232912398b816398bc6da687cL496)), but since you have removed it, it's another dead code.

**Comment by hoxxep** [comment]
I'm on mobile, but if I remember correct `.waves-rippling` is used to check whether a ripple has started to be removed yet (eg. If it has the class then it's still an active ripple). It's (should be) used by the `Effect.hide` function and probably added in `Effect.show`. I'm on mobile though, so I might be misremembering it.

**Comment by cody1991** [comment]
I also find this bug ~ click very fast and create the bug ' Cannot read property 'classList' of undefined' ' , just add  if (!ripple) return ; ?

**Comment by fians** [comment]
I think I spot the problem. As @cody1991 (I don't know why I can't see his comment) said, it seems when we click element multiple times in short time (fast click), the `Effect.hide()` sometimes missing the ripple, because it's already removed by previous click event (which also trigger `Effect.hide()`).

It's like,

_"Hey, I got the ripple A, I will delete it soon by using `setTimeout()`"._ 

_"Hey I get triggered again, I got the ripple A, I will delete it soon... Oops, it's gone, I cannot find it"_.

**Comment by cody1991** [comment]
because i find just add the 
if (!ripple) {
     return;
}
the bug is also exist....
so i delete my comment
~so sorry~

**Comment by fians** [comment]
@cody1991 no, it's fine. :+1:

**Comment by sqal** [comment]
Yeah, it is one solution. But my question still stands. I don't see any reason to adding `waves-rippling` class now. If you simply replace in line [177](https://github.com/fians/Waves/blob/master/src/js/waves.js#L177) class `waves-rippling` to `waves-ripple` then the bug is gone :)
