### ISSUE TITLE
Bower install command at http://fian.my.id/Waves/ incorrect

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [fians/Waves#120]
I tried to copy the bower install command from http://fian.my.id/Waves/#start, but it does not work. It has an uppercase `W` in the package name, and it won't install.

Says: `bower install Waves`.
It appears that it should be: `bower install waves` (lowercase `w`).

Not sure if this resides in the github repo, so I can't send a PR.

**Comment by fians** [comment]
Fixed. :wink:
