### ISSUE TITLE
Not working with Ionic Framework

### ISSUE THREAD

**Issue by bradmartin** [fians/Waves#124]
Not sure if you intend to support mobile frameworks (version 0.6.4 worked fine).

I haven't had time to dig into the code to see what's throwing off the ripple effect but switching from version 0.6.4 to 0.7.2 breaks the effect. No errors logged in the console so possibly a collision with something Ionic does for mobile/touch events.

**Comment by fians** [comment]
Can you share your code here?

**Comment by bradmartin** [comment]
I'll try to put together a plunker/jsBin and see if the issue remains, I'll post the plunkr here when I get to it.

**Comment by dniccum** [comment]
I am seeing the same issue.

**Comment by bradmartin** [comment]
I haven't had any time to setup a codepen or plunkr. I'll try to but no
guarantee.

**Comment by fians** [comment]
There is major break change from 0.6.* to 0.7.*. I'm not sure what library do you using, but there is possibility that the library didn't upgrade Waves version into the new one.

**Comment by bradmartin** [comment]
http://codepen.io/ionic/pen/CbBsA?editors=101 first codepen in awhile. The links to your example page are where I tried to path the .css and .js for Waves from, they might be off. You could tweak those to be accurate if you want to investigate why the effect is not working. I'll take a look at it later if I have the time, no guarantees right now. Thanks for the lib @fians, it's pretty slick and performance has not been an issue for me with 0.6.4. It works great with an Ionic app.

**Comment by bradmartin** [comment]
Ignore that, I don't have a codepen account so it didn't save. Sorry. I'll try to create something workable later.
