### ISSUE TITLE
PhantomJS bind problem

### ISSUE THREAD

**Issue by rkusuma** [fians/Waves#126]
Hi..

I want to test my web using karma and phantomJS, but got error "TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')".
I add bind-polyfill.js but still not working. The problem is in this line of code

``` javascript
var $$               = document.querySelectorAll.bind(document);
```

Any solution ?

**Comment by atardadi** [comment]
+1

**Comment by DavidFrahm** [comment]
+1

This seems to need some conditional checking on the `document` so that it can work when run headless.

Something like this:

```
var $$ = document ? document.querySelectorAll.bind(document);
```

**Comment by wonsikin** [comment]
+1

**Comment by LordZardeck** [comment]
Use PhantomJS2. Earlier versions of PhantomJS do not have `Function.prototype.bind`. If you can't use PhantomJS2, you'll need to include a shim for `.bind`, but I highly recommend updating.

**Comment by fians** [comment]
Thanks @LordZardeck for the answers. I'm closing this issue. But if the problem still happening, feel free to open the new one.
