### ISSUE TITLE
Waves for Radio / checkbox elements

### ISSUE THREAD

**Issue by Shehab-Eltawel** [fians/Waves#127]
Hello, 
I tried to attach waves to radio buttons but it din worked. any ideas ?! 

Thanks

**Comment by fians** [comment]
Sorry, it's seems not possible. The only way to do this might be by creating a custom checkbox element with `<div>` tag.

**Comment by hoxxep** [comment]
You don't add the Waves effect directly onto the `<input type="radio">`, instead you add it to a wrapper or the label:

```html
<label for="r1" class="waves-effect">
    <input id="r1" type="radio" value="value1" name="r">
    Radio box 1
</label>

<label for="r2" class="waves-effect">
    <input id="r2" type="radio" value="value2" name="r">
    Radio box 2
</label>
```

**Codepen:** http://codepen.io/anon/pen/Pqjrax

The labels are required to allow the user to click on the text, which then selects the radio/input button.

**Comment by Shehab-Eltawel** [comment]
@hoxxep  No dear it won't. it will give waves effect for the whole label n input , which isn't what I want to achieve.
what i want to do for checkboxes n radio like the following demo:
 http://fezvrasta.github.io/bootstrap-material-design/#checkbox

I will close this issue, and will re open it if i could get it done with waves.js

Thanks.
