### ISSUE TITLE
Waves.js works wrong when both <button> was disabled and <button> has child.

### ISSUE THREAD

**Issue by lixiaoyan** [fians/Waves#133]
A very simple example: <http://jsbin.com/gofewazula/edit?html,output>.
When disabled `<button>` has child, and you clicked that child, ripple effect works wrong.

**Comment by lixiaoyan** [comment]
Seem to be waves.js only checked the `event.target.disabled`, when I set `child.disabled` to `true`, all things works fine.

**Comment by fians** [comment]
Well, I think I just make the ripple didn't show if there is `disabled` property on target element.
