### ISSUE TITLE
AngulaJS instead of JQuery

### ISSUE THREAD

**Issue by jamesbyrneiitd** [fians/Waves#134]
Any possibility of having it work for AngularJS instead of JQuery?

Would love to see an AngularJS version too.

**Comment by hoxxep** [comment]
Waves does not use jQuery, and it already works alongside angular. You need to use the [$window](https://docs.angularjs.org/api/ng/service/$window) directive to access/initialise it, like so:

```javascript
angular.module('windowExample', [])
    .config([function() {
      // angular module config
    }])
    .run(['$rootScope', '$window', function($rootScope, $window) {
      // initialise waves
      $window.Waves.init();
    }]);
```

Or simply have a separate `<script>` tag to initialise Waves on the HTML template.

---

**Potential issue:** Waves uses a delegated click handler to check if an object with the class `.waves-effect` has been clicked, and then will fire a wave inside. I will warn you, the behaviour is untested on elements which are bound by angular (although one-time bindings will be fine). So if you have a button which changes text, and a waves effect is triggered on that button, I'm not entirely sure what would happen. The simple solution is to bind the text inside a `<span>` tag and you shouldn't have any problems then.

```html
<button class=waves-effect>
    {{ angularTextBinding }}
    <div class=waves-ripple><!-- this div is injected during animation --></div>
</button>
```

I've never tried it, so I don't know if the above would have an issue; but as I said, putting a `<span>` around the binding should fix it if there was an issue.

**Comment by fians** [comment]
Hi @jamesbyrneiitd, I will close this issue since you didn't give the response more than a week. Let us know if @hoxxep's solution working or not.

**Comment by himanshushankhala** [comment]
The dynamic elements in the new view templates are not getting initialize by $window.Waves.init()

Is there any way I can use it, I want to use it. #urgent
