### ISSUE TITLE
Waves.attach only if not already attached

### ISSUE THREAD

**Issue by karlingen** [fians/Waves#136]
Is it possible to make `Waves.attach` to attach only if it has not been attached yet?
The reason I want this is because I'm calling Waves.attach on page load and after an ajax request:

``` coffeescript
$(document).ready ->
  initialize_waves()

  $(document).ajaxSuccess (data)->
    initialize_waves()

initialize_waves = ()->
  config =
    duration: 500
    delay: 50
  # Panels
  Waves.attach '.panel-heading .panel-actions a.panel-button', [
    'waves-button'
    'waves-light'
  ]
  Waves.attach '.panel-heading .panel-actions a i', [
    'waves-circle'
    'waves-light'
  ]
```

This ends up making the element to have the same class multiple times. It's not a problem per se, but it makes the rendered HTML look nasty and wierd and could lead to potential problems (? IE anyone ?)

**Comment by fians** [comment]
Ok. I get it. It seems Waves only prevent duplicated `.waves-effect` class on the element, not other classes that being added in second parameter.

**Comment by lukas-vollmer** [comment]
Same problem. Is there already a solution? E.g in the 0.8 dev version?

**Comment by fians** [comment]
Added to v0.8.0
