### ISSUE TITLE
waves always appear from top left corner

### ISSUE THREAD

**Issue by ahmedali5530** [fians/Waves#137]
Hi @fians 
I m using waves with bootstrap, my problem is that waves always appear from top left corner of button, but it is working well on other elements.
this is what i m using
```
<a href="#!" class="btn btn-primary waves-light waves-button waves-effect pull-right">More...</a>
```
Any help?

**Comment by fians** [comment]
There is little bit conflict if you want to combine Waves with Bootstrap button, since bootstrap have their own button style and sometimes it prevent Waves to work properly. The best way to solve this is by making sure you didn't combine Waves with Bootstrap on your button.

**Comment by ahmedali5530** [comment]
Thanks i got it.
