### ISSUE TITLE
a tag would not ripple because index:-1

### ISSUE THREAD

**Issue by zhiyishou** [fians/Waves#142]
I saw you add `z-index:-1` on a tag for bug in Firefox, but with my test, the version `0.7.4` **couldn't ripple** that is just caused by `z-index:-1`, and my Chrome version is 6.0.2490.71, Firefox version is 41.0.1, besides I haven't seen the bug that there is not triggered in Firefox you said.

**Comment by fians** [comment]
Can you share your code in jsfiddle?

**Comment by ozzywadd** [comment]
I also had this same issue. I'm working with the foundation 6 framework and -1 z-index was causing the ripple effect to be hidden. Removing this is currently working in both Chrome and Firefox latest versions.

**Comment by jonathanmaloy** [comment]
https://jsfiddle.net/pfnghsw9/4/

Moved the following to top of css so you can easily remove to see the ripple working without that line and not working with it.  I removed that line for my project and links are still triggered in all browsers.
    a.waves-effect .waves-ripple {
        z-index: -1;
    }

**Comment by fians** [comment]
Oh, it's my mistake then. If it works all across browser, I will remove it immediately. Thanks.
