### ISSUE TITLE
.attach(elements) doesn't accept array of elements.

### ISSUE THREAD

**Issue by samkelleher** [fians/Waves#148]
The documentation indicates that the `attach()` method accepts an 'array of DOM elements'.

However this no longer functions. Passing in an array of DOM elements does nothing. Internally I believe the array is replaced with an empty array in `getWavesElements` function, shown below.

```
var stringRepr = toString.call(nodes);

        if (stringRepr === '[object String]') {
            return $$(nodes);
        } else if (isObject(nodes) && /^\[object (HTMLCollection|NodeList|Object)\]$/.test(stringRepr) && nodes.hasOwnProperty('length')) {
            return nodes;
        } else if (isDOMNode(nodes)) {
            return [nodes];
        }
```

```
toString.call(rowItemElements);
"[object Array]"
```

Seen above, an array of DOM elements will not match any of the above if statements.

**Comment by fians** [comment]
Good point! Thanks :+1:
