### ISSUE TITLE
Bug in Mozilla Firefox

### ISSUE THREAD

**Issue by softshape** [fians/Waves#156]
When clicking on round buttons, the wave randomly fills the whole square so one can see the corners.

See the video capture here - https://www.youtube.com/watch?v=PF9Bj42nU9M

Recorded in the latest Firefox 46.0.1 on Windows.

**Comment by softshape** [comment]
Just found the same bug on iPad's Google Chrome. So it's not only on Mozilla.

**Comment by fians** [comment]
Hi @softshape, I know it has been a long time, but is the issue still happen in recent version of the browsers? Because I don't see it on Firefox 52.0.1

**Comment by fians** [comment]
Sorry, since there is no response from the issue creator. I have to going to close this issue. Feel free to open in again.
