### ISSUE TITLE
.waves-circle: mismatched property value

### ISSUE THREAD

**Issue by Kaishiyoku** [fians/Waves#157]
Hi,

the .waves-circle class is no longer working (v0.7.5).

When I look inside the waves.scss there appears the following error:
![phpstorm_2016-05-25_20-17-22](https://cloud.githubusercontent.com/assets/5131112/15551338/c707d7e4-22b5-11e6-9726-2cdc9ec998f2.png)

![2016-05-25_20-20-17](https://cloud.githubusercontent.com/assets/5131112/15551404/26a34102-22b6-11e6-8035-344cd697cabb.gif)

**Comment by fians** [comment]
Hi @Kaishiyoku, what browser (and its version) do you use?

**Comment by fians** [comment]
Sorry, since there is no response from the issue creator. I have to going to close this issue. Feel free to open in again.
