### ISSUE TITLE
RequireJS and Waves not showing Click effect

### ISSUE THREAD

**Issue by dave-k** [fians/Waves#160]
I am using Waves with requirejs and material admin (normalize.css) but not seeing the Click effect on buttons.
waves.js is loaded but the waves-effect class is not added to the buttons.

```
<button class="btn btn-default btn-icon"><i class="zmdi zmdi-home"></i></button>
```

Any help/suggestions appreciated.

This is the requirejs configuration.

```
require.config({
    packages: [{
        name: 'waves',
        location: 'assets/libs/waves',   // relative to baseUrl
        main: 'waves'             // relative to package location
    }]
});

require(["waves"], 
    function(Waves) {
        console.log("require Waves ", Waves);
    }
);
```

**Comment by fians** [comment]
Have you tried to add Waves using `Waves.init()` and `Waves.attach()`?

**Comment by fians** [comment]
Sorry, since there is no response from the issue creator. I have to going to close this issue. Feel free to open in again.
