### ISSUE TITLE
Warning: Path must be a string. Received null Use --force to continue.

### ISSUE THREAD

**Issue by cobopanda** [fians/Waves#164]
when I run grunt
outputing this: 
Running "jshint:files" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.

Aborted due to warnings.

**Comment by shourya23** [comment]
reporterOutput: ''             // <-- Add an empty String here

This solution worked for me. If not defined it takes the value as null.

**Comment by Beee4life** [comment]
thanks @shourya23 that did it for me as well.

**Comment by fians** [comment]
I will add this.

**Comment by peternewman** [comment]
You can also fix this by updating jshint to e.g.
`"grunt-contrib-jshint": "^0.12.0",`

**Comment by Kameals** [comment]
thanks @peternewman it works for me.
