### ISSUE TITLE
not working with SVG elements

### ISSUE THREAD

**Issue by Zerelt** [fians/Waves#166]
I have a svg element with a couple of circles inside it on a React page. I wanted to add the awesome wave effect to the circles inside the svg. Would this be possible ? 
   I tried with the circles animated (moving left and right 5px continously) and static but it didn't work even though I saw the class added to the circle in the devtools. I tried manually adding ' waves-effect ' as a className like I did to the elements in the navbar(it works on the navbar) , but that didn't work either for the svg element.

**Comment by fians** [comment]
Hi @Zerelt, it's related with `element.parentElement` issue that being use in Waves.js. I'm working on it, but it will be fixed on v0.8.0 (next version). #167
