### ISSUE TITLE
getWavesEffectElement iterates over parentElement - should use parentNode instead

### ISSUE THREAD

**Issue by DetlefPeters** [fians/Waves#167]
(original issue copied from materializecss project which uses waves.js)

"Hi,
in waves.js function getWavesEffectElement you iterate over target.parentElement recursively. This leads ot problems in IE11 SVG-Elements where parentElement is undefined. Changing this to target.parentNode works as expected in all browsers.

Kind Regards
Joscha"

I open this issue here because your code is involved.

Best regards,
 Detlef

**Comment by fians** [comment]
Added to v0.8.0

**Comment by tomscholz** [comment]
@fians Where to find v0.8.0 ?

**Comment by fians** [comment]
@tomscholz I don't have fixed timeline for v0.8.0 because I have to works on some features (see https://github.com/fians/Waves/milestone/3). Hopefully it will be released by the end of April 2017.
