### ISSUE TITLE
Clicking very often causes the button to get white

### ISSUE THREAD

**Issue by dangllucas** [fians/Waves#179]
When I click for example the primary Button very often and fast, the waves effect overlap and do not get removed from the element causing it to get white completely.

![2017-11-17_22h38_46](https://user-images.githubusercontent.com/27855488/32970161-1a11878c-cbe8-11e7-85cc-60435defaf01.png)
![2017-11-17_22h38_55](https://user-images.githubusercontent.com/27855488/32970164-1cb0f7ca-cbe8-11e7-8b7f-30fd13a78ce0.png)

**Comment by fians** [comment]
Can you give me some information about browser that you use and the version? Also are you using the latest version of Waves (v0.7.5)? Then it would be great if you can reproduce the issue using jsfiddle or jsbin. Thanks!

**Comment by katriellucas** [comment]
I can confirm this issue, using lastest Waves on Firefox and Brave (Chromiun) causes the below when the mouse is rapidly clicked.

![waves](https://user-images.githubusercontent.com/54755295/96172812-50cc1980-0efd-11eb-9500-3927f2adf08c.gif)

PS: Wave CSS is modified but I tested with unmodified version and this still occurs 

**--- EDIT ---**
I think I solved it, just add `element.addEventListener('dragend', Effect.hide, false);` after `element.addEventListener('mouseleave', Effect.hide, false);` 😐
