### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by DanielRuf** [fians/Waves#183]
A few bugs were fixed since the last release last year. It would be great to have a new release.

**Comment by DanielRuf** [comment]
And it would be better to use a banner plugin instead of updating the year in the comment manually.

**Comment by fians** [comment]
@DanielRuf Yeah, I just make a new release. What is a banner plugin?

**Comment by DanielRuf** [comment]
Regarding the banner:

https://github.com/fians/Waves/commit/45f2d4819b159ea8408e6fdc0b581d4b10439607

https://webpack.js.org/plugins/banner-plugin/

**Comment by DanielRuf** [comment]
https://github.com/fians/Waves/commit/3fd8e8a4bc7a6125cb010e39ee29855eb6b5fb34 can be also automated ;-)

**Comment by DanielRuf** [comment]
As there is a new release now I'll close this issue.
