### ISSUE TITLE
ES6 without loader wrapped around Waves

### ISSUE THREAD

**Issue by DanielRuf** [fians/Waves#184]
So far Waves can not be directly used with other bundlers through import/require as it is wrapped in another loader and not available as pure ES6 module.

At least there are no docs about such a working setup. We've got it working with some extra steps like my PR for the browser environment.

But for the future it would be great to have some docs for webpack and other bundlers that work.

**Comment by fians** [comment]
I like the idea.

**Comment by hAtul89** [comment]
I'm exactly re-writing all my website and use ES6.. and now i understand why this doesn't work... i spent hours to figure this out :sob: :rofl:  :sob: :rofl:  :sob: :rofl:  :sob: :rofl:  :sob: :rofl:  :sob: :rofl:  :sob: :rofl:  :sob: :rofl:
