### ISSUE TITLE
provide some method to get (default) options

### ISSUE THREAD

**Issue by DanielRuf** [fians/Waves#187]
Reference: Swiper.params of https://github.com/nolimits4web/Swiper

See `showAllOptions` at https://danielruf.github.io/swiper-builder/

**Comment by fians** [comment]
Do you means something like `Waves.attach('.button')`? Sorry, I don't get it.

**Comment by DanielRuf** [comment]
No, internally there are some default options. It would be good to have a method to dump them to the console. See the `showAllOptions` example from me using Swiper which has `Swiper.params`.

This is helpful to get the current and default options of an instance, clone it and create a new one based on the other settings (Object.assign and so on).
