### ISSUE TITLE
My own crypto on android phone

### ISSUE THREAD

**Issue by Luky90** [fians/Waves#190]
I'm trying to get the address of the receiver by scanning his qrcode (he printed it on paper) to send him some units of a crypto that I have made using waves platform
The problem is that when I push the scanner method  the camera that is open is the frontal one...i'm trying the same to put the frontal camera on the paper with the qr code but it doesn't read it
I have a samsung galaxy note5 but I've tried also with other devices and always it's opened the frontal camera and it's never possible to get the address of the receiver by qrcode
I have tried to check the camera setting and it's correctly settled on the rear camera
Tx for the answer

**Comment by fians** [comment]
@Luky90 Hi, it seems you are mistaken a cryptocurrency platform with this library. This library has nothing to do with cryptocurrency. I think you will have the solution of your problem if you ask the question in other place. Have a good day!
