### ISSUE TITLE
Waves builder (demo)

### ISSUE THREAD

**Issue by DanielRuf** [fians/Waves#195]
I've built https://builder-toolbox.github.io/waves-builder/

Maybe it is helpful for some people.
It uses localstorage for storing the last input and is made with dat.gui and some other small solutions.

Might just work in modern browsers as I use template literals / strings and some other "special" ES(6) features.

**Comment by lucasvazq** [comment]
AMP version?

**Comment by DanielRuf** [comment]
Why would you want an AMP version? AMP is hosted on Googke servers, does not allow custom JS and is mainly for news websites. I don't recommend AMP.

**Comment by lucasvazq** [comment]
It allows js

**Comment by DanielRuf** [comment]
This is not an option for me. I see no real benefits by hosting this on Google servers.

**Comment by DanielRuf** [comment]
Unneeded complication: https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/

Currently it's directly delivered from https://github.com/builder-toolbox/waves-builder/ using GitHub pages.

**Comment by lucasvazq** [comment]
@DanielRuf the javascript allowed in AMP is very [restricted](https://github.com/ampproject/worker-dom/blob/main/web_compat_table.md). And respect to the other comment, you don't need to store your amp sites in google servers, you can store your sites wherever you want.

**Comment by DanielRuf** [comment]
> AMP version?

Still, not relevant / needed for a demo for a project. I think GitHub Pages is pretty fine.
If you want to create a demo using AMP, you are welcome.
But it is not needed.
