### ISSUE TITLE
More 'material-ish' ripple effect

### ISSUE THREAD

**Issue by npvn** [fians/Waves#50]
The ripple effect should be faster and fade out more naturally. Examples from Google: http://www.polymer-project.org/components/paper-button/demo.html

I found an implementation that looks very similar to Google's examples. However I'm not sure how to integrate the code into Waves: http://codepen.io/anon/pen/okIlh

**Comment by fians** [comment]
Radial gradient effect has been added to Waves ripple (thanks to @hoxxep) and will arrive on v0.6.0. It makes the ripple more natural than the old one.
