### ISSUE TITLE
Auto generate SASS/SCSS file from LESS file

### ISSUE THREAD

**Issue by fians** [fians/Waves#67]
Let's figure how to programmatically generate SASS/SCSS file from LESS file on `grunt build`.

**Comment by hoxxep** [comment]
Take a look at my less2scss branch. SASS, SCSS and Stylus code are all transpiled from the LESS source on `grunt build`. It does make the gruntfile a lot uglier though...

The conversions do work though and they generate the same minified output! :smiley:

**Comment by fians** [comment]
Nice, could you create a pull request of that branch to v0.6.0-dev? Thanks!

**Comment by hoxxep** [comment]
Added pull request #75 which merges the less2scss branch.

**Comment by fians** [comment]
Everything looks fine. But I've changed ripple gradient value (1a216627cdc13a295fb9ede8c5f7de9e758a46ec), just to make sure all css pre-processor script generate same css output.

Thank you!

**Comment by hoxxep** [comment]
Ah cool! Good shout and no problem :)
