### ISSUE TITLE
Add button which has a side-effect on the demo page.

### ISSUE THREAD

**Issue by hoxxep** [fians/Waves#68]
I'll add a button which has a side effect on the demo page (to demonstrate that JS clicks still work on the buttons). I'll see if I can use [SweetAlert](http://tristanedwards.me/sweetalert) because it looks pretty nifty.

**Comment by fians** [comment]
I've checked your Snarl notification, and it works nicely. I will push it to v0.6.0. Thanks for your great project! :smile:
