### ISSUE TITLE
Add delegated mouse/touch handler because dynamically added .waves-effect doesn't work

### ISSUE THREAD

**Issue by hoxxep** [fians/Waves#71]
If Snarl notifications have the `.waves-effect` class added to them, no event listener is bound to them, hence clicking them does not start the waves effect. Waves needs to be fully reloaded every time a dynamic element to be used with `.waves-effect` is added to the document (potentially causing duplicated event listeners).

I'm not sure what the best solution would be, is adding an `addWavesListener` function which takes the added element as a parameter a good way of [manually] adding the extra event listeners?

**Comment by Dogfalo** [comment]
Looking forward to this :smile:

**Comment by hoxxep** [comment]
To solve my own issue, I've added delegated mouse/touch handling to `v0.6.0-dev` in pull request #77. :smile:

As specified in the pull request, `mouseup` and `mouseleave` events are still bound to the element when a `mousedown` occurs (even a programmer probably won't notice). This is because delegating these events is pretty difficult without jQuery (or so I think at least?), and it shouldn't have a noticeable performance hit because people usually only single or double click - so there's never any large number of event listeners.

The programmer won't notice the difference either, as the `mouseup` and `mouseleave` are bound automatically on/after a `mousedown` event, so even dynamically loaded/added HTML elements with the `.waves-effect` will still show the ripple effect.

#### Small issue with dynamically loaded input elements
There is a minor issue with dynamically loaded `input` elements with the `.waves-effect` class. Unless the programmer manually wraps these, he'll have to make Waves re-wrap `input` buttons in the document.

#### Manual binding of traditional event listeners
I also added `Waves.attach(element)` so that if someone doesn't want to use the delegated event listener (aka `Waves.displayEffect()`) they still have the option to manually bind click handlers. Perhaps there's a specific use case this is useful for, but the only reason I could think of dynamically loaded `input` elements. Although, I still think that giving the programmer access to `Effect.wrapInputs()` is an easier/cleaner/better solution for the programmer.

**Comment by fians** [comment]
Added on v0.6.0. Please try it on beta preview here http://fian.my.id/Waves/0.6.0-beta.
