### ISSUE TITLE
Waves doesn't work on Chrome

### ISSUE THREAD

**Issue by fians** [fians/Waves#81]
Waves doesn't work on the site (http://fian.my.id/Waves). Using Chrome 39 on Windows 7.

**Comment by fians** [comment]
It's weird. It works on IE and Firefox. It also works on Chrome 39, when I test it with BrowserStack.

**Comment by hoxxep** [comment]
Probably another duplicate issue with touch screen windows laptops an v0.5.5 again. Again, it should work with v0.6.0 since we've bound both touch and mouse listeners now.

**Comment by fians** [comment]
I think it's time to release v0.6.0.
