### ISSUE TITLE
svg error

### ISSUE THREAD

**Issue by Taximan** [fians/Waves#86]
First I want to note that this is my first issue report ever so don't be to harsh on me. But on to the good or in this case the bad stuff. Mainly, svgs seems to be, for no real reason targeted causing an 
>Uncaught TypeError: undefined is not a function 

It doesn't seems like it would brake anything, just this annoying console message. Here you can see it in action http://codepen.io/anon/pen/MYEgaa open the console click on the div see nothing happening(except the wished ripple effect) but when you click on the svg you get an TypeError.

**Comment by fians** [comment]
Thanks! :smile:
