### ISSUE TITLE
Wrong sources in waves.min.js.map

### ISSUE THREAD

**Issue by urbany** [fians/Waves#90]
Hi, `/dist/waves.min.js.map` points to `sources":["../src/js/waves.js"]` but the `src` directory is not available when installing via Bower.
Can you make it point to the waves file in the `dist` directory? `sources":["waves.js"]`

Thank you in advance.

**Comment by fians** [comment]
I just realized people will need `src` directory when they installing Waves with Bower. So I just remove `src` from ignored list on bower.json. (61485d2afb58ded3ee4dd3704439a080ccfa802c)
