### ISSUE TITLE
animation doesn't finish

### ISSUE THREAD

**Issue by ddtramp** [fians/Waves#93]
the browser is webkit core ;  android  cell phone
my code is

    <a href="tel:123456789" class="waves-effect waves-button">click here</a>

when click this button, the browser default action is pop-up  notice and will be stop the waves effect,

when trigger focus out event on this element,  the waves effect will be continue to implement.

but when finish,  this part of the text on the button will be covered , it's look like this

**Comment by fians** [comment]
Can you give me some screenshots of it or sample of your code?

**Comment by ddtramp** [comment]
i have find a way to solve this problem

i change this `Effect.hide()` method

         // el.removeChild(ripple);
         el.removeChild(ripple.getSetAttribute('style', convertStyle({display: 'none'}))); // i add this line

i found use `el.removeChild()` method doesn't work at android operating system, but use `ripple.remove()` or `el.lastChild.remove()` is ok,  

unfortunately, `remove()` is not w3 standard method

**Comment by fians** [comment]
Thanks for finding a bug. I will take a look at it later today.

**Comment by fians** [comment]
Could you tell me the version of android device when you saw this bug?

**Comment by ddtramp** [comment]
android version: 4.1.1 JRO03L;
MIUI VERSION: MIUI-JLB52.0

and i found this bug in wechat app on android device. this app use own browser Rendering Engine base on webkit

**Comment by fians** [comment]
Sorry, I cannot replicate the bug. But can you try to test [this fiddle](http://jsbin.com/kaxequlipe/1/) with the device browser (default one)? Just to make sure if it's working or not. Thanks.

**Comment by ddtramp** [comment]
i try, you code will run correctly, but I still have this problem.

**Comment by ddtramp** [comment]
![1](https://cloud.githubusercontent.com/assets/4402625/6613611/75195aa2-c8ca-11e4-9f5e-a327f0bbc4d8.PNG)
![2](https://cloud.githubusercontent.com/assets/4402625/6613617/89311110-c8ca-11e4-90f6-2092828bebe9.PNG)
![3](https://cloud.githubusercontent.com/assets/4402625/6613622/92088b9c-c8ca-11e4-9689-78fa1bad8fbe.PNG)


like this

**Comment by hoxxep** [comment]
If you press with two or three fingers, it's starts two or three ripples but will only stop one because as far as I remember it only fires the touch up/end event when all touches have ceased? Perhaps this is the problem?

Try it on the Waves header, press on it with multiple fingers then lift them all off and you'll see one or two ripples don't disappear? (It happens on iOS, not sure about android). 

I'm just thinking maybe his browser is registering multiple touches for one touch and that's causing this issue for him?

**Comment by ddtramp** [comment]
This bug appears in wechat app, android version, ios verison is ok;

and this app use tencent QQ browser x5 kernel, maybe there change something...

**Comment by fians** [comment]
I think it's better to close this issue, since the bug happen inside closed-sourced browser and hard to replicate. Thanks for your feedback @ddtramp! :smile:
