### ISSUE TITLE
Disable waves animation when scrolling

### ISSUE THREAD

**Issue by Bbemol** [fians/Waves#95]
Hi! Thanks for this great effect.
It exists already in materializecss actually, but it's good to have minimal functionalities such as these.

On mobile, I would like the effect to be disabled when you scroll.
For example : I have a sidebar with navigation link. If I scroll down and the finger initial position is on your wave animation then it will run the animation but I don't want it to run.

So do you think it's possible to make animation run only on simple tap and not long tap ?
Thanks again.
Benjamin.

**Comment by hoxxep** [comment]
You can see issue #89 for why this isn't possible. Delaying the waves effect for long/short touches isn't possible: if we hold a button for example, we want the waves effect to have occurred as soon as the user touches. But then the user can decide to scroll after holding the button for a second or two. There's no clean way of checking whether the user is scrolling without [significantly] delaying the waves effect, which spoils the aesthetic in almost every other use case.

**Comment by Bbemol** [comment]
Oh sorry, I didn't check well the existing issue. Thanks for your reply. Keep doing your good job.

**Comment by hoxxep** [comment]
No worries! It's quite a common request, with sadly no easy or currently known viable fix.
