### ISSUE TITLE
Shadow flicker when button pressed

### ISSUE THREAD

**Issue by sodbileg** [fians/Waves#96]
Hi, 
When I click on a button, it flickers on the right side like a video below if I set `font-weight` of a button to `500`.

Button html: `<input type="submit" class="waves-effect waves-button waves-float" value="search">`

[Video](https://www.dropbox.com/s/xnu688un8465wy2/Untitled1.mov?dl=0)

**Comment by fians** [comment]
Got it. I'll investigate this issue. Thanks.

**Comment by shamank** [comment]
Hi. Same here. It's something related to the width or padding of the element, because changing that it solves the issue. In my case, it's also happening at bottom. Thanks!

**Comment by fians** [comment]
Sorry for being leaving this issue unresolved in a long time. Currently I didn't find this issue on my machine (macOS 10.12.6 Chrome & Firefox). Feel free to open this issue if you still find the shadow flicker.
