### ISSUE TITLE
Mixin names conflict with Compass-css

### ISSUE THREAD

**Issue by marcinant** [fians/Waves#97]
Mixins: transition, transform, box-shadow conflict with mixins defined by [Compass](http://compass-style.org/reference/compass/css3/)

These names are too common.

My feature requests are:

- Rename mixins

and/or

- Use Compass instead of custom mixins

**Comment by hoxxep** [comment]
We don't want to add extra dependencies, and I can see how the mixins can affect people. I'll rename the mixins tonight/tomorrow by adding a `@waves-` suffix.

**Comment by fians** [comment]
@hoxxep Let me handle it.

**Comment by fians** [comment]
Fixed :wink:
