### ISSUE TITLE
Waves Don't Show Over Zeroclipboard

### ISSUE THREAD

**Issue by danielhickman** [fians/Waves#98]
The things changing in the HTML that you can see are Zeroclipboard adding active and hover classes to the `<a>` tag and the wave-ripple `<div>` elements appearing. This issue is Zero's flash movie interferes with the waves element.
URL: http://materialcolorize.com/color-picker/
Browser: Chrome 42.0.2311.39 beta-m (64-bit)
System: Windows 8.1 Machine

![desktop 03 13 2015 - 22 10 49 01_1](https://cloud.githubusercontent.com/assets/5341898/6650427/582fd42a-c9ce-11e4-90d2-8742f0f9b60b.gif)

**Comment by fians** [comment]
This happen because Zeroclipboard overlay the waves element with transparent flash. You might be want to take a look this issue https://github.com/zeroclipboard/zeroclipboard/issues/536

**Comment by fians** [comment]
Sorry, I have to close this issue since you didn't give me any response for last 7 days. Thanks!
