### ISSUE TITLE
Can't See Effect on href elements

### ISSUE THREAD

**Issue by shaulhadar** [fians/Waves#99]
Hello, thanks for this great project!  for some reason, i can't make it work on list item or items that have href tag... is there any way to achieve this?

thanks :)

**Comment by fians** [comment]
Can you replicate the bug using jsfiddle?

**Comment by shaulhadar** [comment]
Hi Fians, thanks for getting back to me.  I couldn't made a jsfiddle demo, so i uploaded the folder to a subdomain, so you can see...  i have waves effects on the menu items, but only the most bottom one is working... also , the effect didn't work on the posts, but i kind of hacked it to work, but not 100%...

here is the test site, based on wpionic...:

http://sh-original-media.com/wavesdemo/

Thanks :)

**Comment by fians** [comment]
Well, Waves effect didn't show because Ionic adding `.activated` class when you click the list, and `.activated` contain `background-color` property. Here is the css value of `.activated`:

```
.item.active, .item.activated, .item-complex.active .item-content, .item-complex.activated .item-content, .item .item-content.active, .item .item-content.activated {
  border-color: #ccc;
  background-color: #D9D9D9;
}
```

Try to override this behaviour by setting `background-color` to `transparent` to show the ripple. Add this to your css to fix it.

```
.item.active, 
.item.activated, 
.item-complex.active .item-content, 
.item-complex.activated .item-content, 
.item .item-content.active, 
.item .item-content.activated {
  background-color: transparent;
}
```

**Comment by shaulhadar** [comment]
Hi Fians, your method almost fixed the problem.  I have made another test here:

http://sh-original-media.com/wavesdemo2

the effect now shows on the menu items, but for some reason, it vanishes as soon as you move your finger, while in other places it has a fade in the animation effect... but at least now i can see the animation.   but there is another problem, for some reason, the animation doesn't show on the posts in the list on the first page of the app.... is it another .activated class? because i couldn't find it.

Please let me know how I can fix this.

Thanks :)

**Comment by fians** [comment]
Sorry, I've been busy in the last couple weeks. Do you still have this issue?

**Comment by shaulhadar** [comment]
Hi, Yes, i still have this issue.. is there anything i can do ?
 


     On Friday, April 10, 2015 4:12 PM, Alfiana Sibuea <notifications@github.com> wrote:
   

 Sorry, I've been busy in the last couple weeks. Do you still have this issue?—

**Comment by fians** [comment]
First, you should add space between your css value and `!important` property. Please take a look your style.css on line 117. And it seems you are using old version of Waves, try to update to the latest one v0.6.6.

**Comment by fians** [comment]
Sorry, I have to close the issue, because you haven't give response in last 7 days. Feel free to give your comment if you want to reopen this issue. Thanks!

**Comment by shaulhadar** [comment]
Thanks for your help man!!
 


     On Sunday, April 19, 2015 4:09 PM, Alfiana Sibuea <notifications@github.com> wrote:
   

 Sorry, I have to close the issue, because you haven't give response in last 7 days. Feel free to give your comment if you want to reopen this issue. Thanks!—
